### ISSUE TITLE
future incompatibility of iso-rs v0.1.3

### ISSUE THREAD

**Issue by ADannadata** [dashxhq/iso-rs#1]
the following packages contain code that will be rejected by a future version of Rust: iso-rs v0.1.3
caused by
```
warning: trailing semicolon in macro used in expression position
```

**Comment by RabidFire** [comment]
This has been released in [v0.1.4](https://crates.io/crates/iso-rs/0.1.4) - Thanks @ArthurMatthys @ADannadata @sumeetattree
